- name: Restart systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Reload transmission
  ansible.builtin.service:
    name: transmission
    state: reloaded

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

- name: Restart ip6tables
  ansible.builtin.service:
    name: ip6tables
    state: restarted

- name: Restart mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: Reload nfs exports
  ansible.builtin.command:
    cmd: exportfs -ra

- name: Restart home-assistant
  community.general.docker_container:
    name: home-assistant
    restart: true
    comparisons: { "*": ignore }

- name: Restart appdaemon
  community.general.docker_container:
    name: appdaemon
    restart: true
    comparisons: { "*": ignore }

- name: Sync personal repo database
  ansible.builtin.shell:
    cmd: "repo-add --remove --new /srv/pkgs/personal.db.tar.gz /srv/pkgs/*.pkg.tar.xz"

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Sync pacman cache
  community.general.pacman:
    update_cache: true
