---
- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted

- name: reload smbd
  service: name=smbd state=reloaded

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload nfs exports
  command: exportfs -ra

