---
- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted

- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload transmission
  service: name=transmission state=reloaded

- name: reload nfs exports
  command: exportfs -ra

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart mosquitto
  service: name=mosquitto state=restarted

- name: restart home-assistant
  docker_container:
    name: home-assistant
    restart: yes
    comparisons: { "*": ignore }

- name: restart appdaemon
  docker_container:
    name: appdaemon
    restart: yes
    comparisons: { "*": ignore }

- name: sync personal repo database
  shell: "repo-add --remove --new /srv/pkgs/personal.db.tar.gz /srv/pkgs/*.pkg.tar.xz"

- name: systemd daemon-reload
  systemd: daemon_reload=yes

- name: sync pacman cache
  pacman: update_cache=yes
