---
- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted

- name: reload smbd
  service: name=smbd state=reloaded

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload transmission
  service: name=transmission state=reloaded

- name: reload nfs exports
  command: exportfs -ra

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart homebridge
  service: name=homebridge state=restarted

- name: sync pacman cache
  pacman: update_cache=yes
