- name: Add archzfs repo key
  community.general.pacman_key:
    id: DDF7DB817396A49B2A2723F7403BD972F75D9D76
    url: https://archzfs.com/archzfs.gpg
    state: present

- name: Add arch ZFS repo
  ansible.builtin.copy:
    src: archzfs-repo
    dest: /etc/pacman.d
    mode: "0644"

- name: Include archzfs repo in pacman.conf
  notify: Sync pacman cache
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    line: "Include = /etc/pacman.d/archzfs-repo"

- name: Install archzfs-linux
  community.general.pacman:
    name: archzfs-linux

- name: Create zfs-list.cache directory
  ansible.builtin.file:
    path: /etc/zfs/zfs-list.cache
    state: directory
    mode: "0755"

- name: Enable ZFS services
  with_items:
    - zfs.target
    - zfs-import.target
    - zfs-import-cache.service
    - zfs-zed.service
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true

- name: Create zfs-list.cache/documents
  ansible.builtin.file:
    path: /etc/zfs/zfs-list.cache/documents
    state: touch
    mode: "0755"
    modification_time: preserve
    access_time: preserve
