---
- name: Install packages
  yum: name={{ item }}
  with_items:
    - bash-completion
    - git

- name: Configure iptables
  copy: src=iptables dest=/etc/sysconfig/
  notify: restart iptables

- include: socat-tunnel.yml
