- name: Install opencode
  kewlfft.aur.aur:
    name: opencode-bin
    state: present
  become: true
  become_user: aur-builder

- name: Install opencode-ssh-agent-proxy script
  ansible.builtin.copy:
    src: opencode-ssh-agent-proxy
    dest: /usr/local/bin/opencode-ssh-agent-proxy
    mode: "0755"

- name: Install opencode-ssh-agent-proxy systemd units
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: "0644"
  loop:
    - opencode-ssh-agent-proxy.socket
    - opencode-ssh-agent-proxy@.service
  notify: Systemd daemon-reload

- name: Install opencode-ssh-agent-proxy SSH key
  ansible.builtin.copy:
    content: "{{ opencode_ssh_agent_proxy_key }}"
    dest: /etc/opencode-ssh-agent-proxy-key
    mode: "0600"
    owner: root
    group: root

- name: Enable opencode-ssh-agent-proxy socket
  ansible.builtin.service:
    name: opencode-ssh-agent-proxy.socket
    state: started
    enabled: true
    daemon_reload: true

- name: Install import-environment systemd user service
  ansible.builtin.copy:
    src: import-environment.service
    dest: /etc/systemd/user/import-environment.service
    mode: "0644"
  notify: Systemd user daemon-reload

- name: Get evan user id
  ansible.builtin.command: id -u evan
  register: machines_evan_uid
  changed_when: false

- name: Enable import-environment user service
  ansible.builtin.systemd:
    name: import-environment
    enabled: true
    scope: user
  become: true
  become_user: evan
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ machines_evan_uid.stdout }}"

- name: Install opencode systemd user service
  ansible.builtin.copy:
    src: opencode.service
    dest: /etc/systemd/user/opencode.service
    mode: "0644"
  notify: Systemd user daemon-reload

- name: Enable opencode user service
  ansible.builtin.systemd:
    name: opencode
    state: started
    enabled: true
    scope: user
  become: true
  become_user: evan
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ machines_evan_uid.stdout }}"
