# Manages: ArchLinux on hardware
#
# This playbook configures my 'htpc' media center PC. For more details on this
# configuration see my media-center-automation documenation [1].
#
# [1]: https://github.com/EvanPurkhiser/media-center-automation

---
- hosts: htpc.home.evanpurkhiser.com
  roles:
  - common
  - pacsync
  - wireless
  - systemd-timesyncd
  - personal-repo
  - machines/htpc
