# Manages: ArchLinux on hardware. This playbook configures my 'home' server.
#
# This server has a few purposes:
#
# - Serve my large storage disk over NFS and Samba.
# - Run the transsmission torrent daemon
# - Serve the transmission rpc interface through a nginx proxy
# - Serve a small public-share directory

---
- hosts: server.home.evanpurkhiser.com
  roles: [ machines/server ]
