- name: Add evanpurkhiser package signing key
  community.general.pacman_key:
    id: DE0CDD0EBA7CBA65BC23BA28E9A664529E7CACFB
    keyserver: keyserver.ubuntu.com
    ensure_trusted: true
    state: present

- name: Add evanpurkhiser pacman repo conf
  ansible.builtin.copy:
    src: evanpurkhiser
    dest: /etc/pacman.d/evanpurkhiser
    mode: "0644"

- name: Include evanpurkhiser repo in pacman.conf
  notify: Sync pacman cache
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    line: "Include = /etc/pacman.d/evanpurkhiser"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
