- name: Install things3-cloud from evanpurkhiser pacman repo
  notify: Restart things3-server
  community.general.pacman:
    name: things3-cloud
    state: present

- name: Install Things3 auth environment file
  notify: Restart things3-server
  ansible.builtin.template:
    src: things3-auth.conf.j2
    dest: /etc/things3-auth.conf
    mode: "0600"
    owner: root
    group: root

- name: Enable things3 server service
  ansible.builtin.service:
    name: things3-server.service
    state: started
    enabled: true
    daemon_reload: true
