- name: Install agent-witness from evanpurkhiser pacman repo
  notify: Restart agent-witness
  community.general.pacman:
    name: agent-witness
    state: latest

- name: Install agent-witness config
  notify: Restart agent-witness
  ansible.builtin.copy:
    src: agent-witness.toml
    dest: /etc/agent-witness.toml
    owner: root
    group: root
    mode: "0600"

- name: Configure agent-witness socket group
  notify: Restart agent-witness
  ansible.builtin.copy:
    src: socket-group.conf
    dest: /etc/systemd/system/agent-witness.service.d/
    owner: root
    group: root
    mode: "0644"

- name: Enable agent-witness service
  ansible.builtin.systemd:
    name: agent-witness.service
    state: started
    enabled: true
    daemon_reload: true

- name: Expose agent-witness internally
  notify: Reload nginx
  internal_service:
    name: agent-witness
    local_port: 9345
