title: Apartment
resources:
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/community/simple-weather-card/simple-weather-card-bundle.js
    type: module

views:
  - title: 'Home'
    icon: 'mdi:home'
    panel: false
    path: default_view

    cards:
      - type: entities
        title: Livingroom
        show_header_toggle: false
        entities:
          - entity: light.living_room_lights
            tap_action: { action: toggle }
          - entity: cover.living_room_shades
          - entity: fan.xiaomi_miio_device
            tap_action: { action: toggle }

      - type: entities
        title: Kitchen
        entities:
          - entity: light.kitchen_lights
            tap_action: { action: toggle }
          - entity: light.kitchen_cove_lights
            tap_action: { action: toggle }

      - type: custom:mini-graph-card
        name: Temperature
        entities:
          - entity: sensor.apartment_temperature
            name: Inside Temperature
            show_legend: false
          - entity: sensor.dark_sky_temperature
            name: Outside Temperature
            show_legend: false
        points_per_hour: 0.5
        hours_to_show: 48
        font_size: 75

      - type: custom:mini-graph-card
        name: Air Quality
        entities: [sensor.xiaomi_pm25]
        icon: 'mdi:weather-windy'
        hours_to_show: 48

      - type: custom:simple-weather-card
        entity: weather.smhi
        name: " "
        backdrop: true
