homeassistant:
  name: Apartment
  time_zone: America/Los_Angeles
  unit_system: metric
  elevation: 16
  latitude: 37.765389
  longitude: -122.410831
  external_url: https://hass.evanpurkhiser.com

http:
  use_x_forwarded_for: true
  trusted_proxies: [127.0.0.1]

automation: !include automations.yaml

config:
history:
logbook:
mobile_app:
system_health:
lovelace:
my:

frontend:
  themes: !include_dir_merge_named themes

homekit:

google_assistant:
  project_id: home-assistant-19f4f
  service_account: !secret google_assistant_service_account
  report_state: true
  expose_by_default: true

climate:
  - name: Living Room
    unique_id: livingroom_thermostat
    platform: generic_thermostat
    heater: switch.livingroom_heater
    target_sensor: sensor.livingroom_temperature
  - name: Bedroom
    unique_id: bedroom_thermostat
    platform: generic_thermostat
    heater: switch.bedroom_heater
    target_sensor: sensor.bedroom_temperature
