homeassistant:
  name: Apartment
  time_zone: America/New_York
  unit_system: metric
  elevation: 13
  latitude: 40.721690
  longitude: -73.979350
  external_url: https://hass.evanpurkhiser.com

http:
  use_x_forwarded_for: true
  trusted_proxies: [127.0.0.1]

automation: !include automations.yaml

config:
history:
logbook:
mobile_app:
system_health:
lovelace:
my:

frontend:
  themes: !include_dir_merge_named themes

