homeassistant:
  name: Apartment
  time_zone: America/New_York
  unit_system: metric
  elevation: 13
  latitude: 40.721690
  longitude: -73.979350
  external_url: https://hass.evanpurkhiser.com

  customize:
    light.donut_light:
      supported_color_modes:
        - brightness
      color_mode: brightness
    light.closet_hanger:
      supported_color_modes:
        - brightness
        - color_temp
      color_mode: brightness
http:
  use_x_forwarded_for: true
  trusted_proxies: [127.0.0.1]

automation: !include automations.yaml
script: !include scripts.yaml

config:
history:
logbook:
mobile_app:
system_health:
lovelace:
my:

frontend:
  themes: !include_dir_merge_named themes

rest_command:
  virtual_doorman_unlock:
    url: "https://op-portal.virtualdoorman.com/g6compatressvcs/door-unlock/1400"
    headers:
      vdmauthtoken: !secret virtual_doorman_token
      user-agent: VirtualDoorman/2.5 (com.vdm.welcomeapp; build:10; iOS 17.4.1) Alamofire/5.8.0

rest:
  - resource: https://www.googleapis.com/youtube/v3/playlistItems
    method: GET
    scan_interval: 1800
    params:
      part: snippet
      maxResults: 50
      playlistId: PLlUsJxfdNKg2PfRqnd_tolL2wbCstoYWQ
      key: !secret youtube_data_api_key
    headers:
      Accept: application/json
    sensor:
      - name: "Morning YouTube Playlist"
        unique_id: youtube_paylist.morning
        value_template: "{{ value_json.pageInfo.totalResults if value_json is defined else 0 }}"
        json_attributes:
          - items

  - resource: https://www.googleapis.com/youtube/v3/playlistItems
    method: GET
    scan_interval: 1800
    params:
      part: snippet
      maxResults: 50
      playlistId: PLlUsJxfdNKg0fKtSk7BRlSzwWbQp0HeEA
      key: !secret youtube_data_api_key
    headers:
      Accept: application/json
    sensor:
      - name: "Evening Chillout YouTube Playlist"
        unique_id: youtube_paylist.evening_chillout
        value_template: "{{ value_json.pageInfo.totalResults if value_json is defined else 0 }}"
        json_attributes:
          - items

  - resource: https://www.googleapis.com/youtube/v3/playlistItems
    method: GET
    scan_interval: 1800
    params:
      part: snippet
      maxResults: 50
      playlistId: PLlUsJxfdNKg0vPTrigsPOvkBADXQlKw-o
      key: !secret youtube_data_api_key
    headers:
      Accept: application/json
    sensor:
      - name: "Nighttime Sleep YouTube Playlist"
        unique_id: youtube_paylist.nightime_sleep
        value_template: "{{ value_json.pageInfo.totalResults if value_json is defined else 0 }}"
        json_attributes:
          - items

  - resource: https://www.googleapis.com/youtube/v3/playlistItems
    method: GET
    scan_interval: 1800
    params:
      part: snippet
      maxResults: 50
      playlistId: PLlUsJxfdNKg3ulS-KtNQh1EYLsiy8XcHl
      key: !secret youtube_data_api_key
    headers:
      Accept: application/json
    sensor:
      - name: "Energized YouTube Playlist"
        unique_id: youtube_paylist.energized
        value_template: "{{ value_json.pageInfo.totalResults if value_json is defined else 0 }}"
        json_attributes:
          - items
