homeassistant:
  name: Apartment
  time_zone: America/New_York
  unit_system: metric
  elevation: 13
  latitude: 40.721690
  longitude: -73.979350
  external_url: https://hass.evanpurkhiser.com

  customize:
    light.donut_light:
      supported_color_modes:
        - brightness
      color_mode: brightness

http:
  use_x_forwarded_for: true
  trusted_proxies: [127.0.0.1]

automation: !include automations.yaml

config:
history:
logbook:
mobile_app:
system_health:
lovelace:
my:

frontend:
  themes: !include_dir_merge_named themes

rest_command:
  virtual_doorman_unlock:
    url: "https://op-portal.virtualdoorman.com/g6compatressvcs/door-unlock/1400"
    headers:
      vdmauthtoken: !secret virtual_doorman_token
      user-agent: VirtualDoorman/2.5 (com.vdm.welcomeapp; build:10; iOS 17.4.1) Alamofire/5.8.0
