homeassistant:
  name: Apartment
  time_zone: America/Los_Angeles
  unit_system: imperial
  elevation: 16
  latitude: 37.765389
  longitude: -122.410831
  external_url: https://hass.evanpurkhiser.com
  allowlist_external_dirs: ["/var/lib/hass-ad"]

http:
  use_x_forwarded_for: true
  trusted_proxies: [127.0.0.1]

config:
history:
logbook:
mobile_app:
system_health:
lovelace:

frontend:
  themes: !include_dir_merge_named themes

homekit:
  filter:
    include_entities:
      - sensor.purifier_pm25
      - climate.apartment
      - cover.living_room_shades
      - cover.evans_window
      - cover.evans_patio_door
      - cover.joes_window
      - cover.joes_patio_door
      - light.living_room_lights
      - light.kitchen_cove_lights
      - light.kitchen_lights
      - light.work_closet_light
      - light.front_foyer_lights
      - light.joes_room_lights
      - light.joes_bedside_light
      - light.evans_room_lights
      - light.evans_room_opal
      - light.evans_bathroom_vanity_lights
      - light.evans_bathroom_tub_light

google_assistant:
  project_id: home-assistant-19f4f
  service_account: !secret google_assistant_service_account
  report_state: true
  expose_by_default: false
  entity_config:
    sensor.purifier_pm25: { expose: true }
    climate.apartment: { expose: true }
    cover.living_room_shades: { expose: true }
    cover.evans_window: { expose: true }
    cover.evans_patio_door: { expose: true }
    cover.joes_window: { expose: true }
    cover.joes_patio_door: { expose: true }
    light.living_room_lights: { expose: true }
    light.kitchen_cove_lights: { expose: true }
    light.kitchen_lights: { expose: true }
    light.work_closet_light: { expose: true }
    light.front_foyer_lights: { expose: true }
    light.joes_room_lights: { expose: true }
    light.joes_bedside_light: { expose: true }
    light.evans_room_lights: { expose: true }
    light.evans_room_opal: { expose: true }
    light.evans_bathroom_vanity_lights: { expose: true }
    light.evans_bathroom_tub_light: { expose: true }

ecobee:
  api_key: !secret ecobee_api_key

lutron_caseta:
  - host: 10.0.0.20
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

zha:
  usb_path: /dev/zigbee
  database_path: /config/zigbee.db

mqtt:
  broker: 10.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1
  birth_message:
    topic: tele/hass1/LWT
    payload: Online
    qos: 1
    retain: false
  will_message:
    topic: tele/hass1/LWT
    payload: Offline
    qos: 1
    retain: false

telegram_bot:
  - platform: webhooks
    api_key: !secret apartment_bot_token
    parse_mode: markdown
    allowed_chat_ids:
      - -427766023 # Apartment chat
      - 1252020315 # Evan DM
      - 1050261397 # Joe DM

octoprint:
  - host: 10.0.0.8
    api_key: !secret octoprint_api_key
    name: Ender 3 V2
    number_of_tools: 1
    bed: true
    sensors:
      monitored_conditions:
        ["Current State", "Job Percentage", "Time Elapsed", "Time Remaining"]

light:
  - platform: template
    lights:
      # Joes desk lamp is currently mapped to switch 1
      joes_bedside_light:
        unique_id: light.joes_bedside_light
        friendly_name: Joe's Bedside Light
        value_template: "{{ states('switch.plug_1') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.plug_1
        turn_off:
          service: switch.turn_off
          entity_id: switch.plug_1

      # The work-closet light is currently mapped to switch 2
      work_closet_light:
        unique_id: light.work_closet
        friendly_name: Work Closet Light
        value_template: "{{ states('switch.plug_2') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.plug_2
        turn_off:
          service: switch.turn_off
          entity_id: switch.plug_2

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast: [1]
    monitored_conditions: [temperature]

  # Dishwasher current monitoring
  - platform: mqtt
    name: "Dishwasher Current"
    state_topic: "dishwasher_plug/tele/SENSOR"
    value_template: "{{ value_json['ENERGY']['Current'] }}"
    device_class: current
    unit_of_measurement: Amps
    availability_topic: "dishwasher_plug/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
  - platform: mqtt
    name: "Dishwasher Power"
    state_topic: "dishwasher_plug/tele/SENSOR"
    value_template: "{{ value_json['ENERGY']['Power'] }}"
    device_class: power
    unit_of_measurement: Watts
    availability_topic: "dishwasher_plug/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1

  # Laundry current monitoring
  - platform: mqtt
    name: "Laundry Current"
    state_topic: "laundry_plug/tele/SENSOR"
    value_template: "{{ value_json['ENERGY']['Current'] }}"
    device_class: current
    unit_of_measurement: Amps
    availability_topic: "laundry_plug/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
  - platform: mqtt
    name: "Laundry Power"
    state_topic: "laundry_plug/tele/SENSOR"
    value_template: "{{ value_json['ENERGY']['Power'] }}"
    device_class: power
    unit_of_measurement: Watts
    availability_topic: "laundry_plug/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1

cover:
  - platform: group
    name: Living Room Shades
    entities:
      - cover.living_room_left_shade
      - cover.living_room_middle_shade
      - cover.living_room_right_shade
