homeassistant:
  name: Apartment
  time_zone: America/Los_Angeles
  unit_system: imperial
  elevation: 16
  latitude: 37.765389
  longitude: -122.410831
  external_url: https://hass.evanpurkhiser.com

http:
config:
history:
logbook:
system_health:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

homekit:
  filter:
    include_entity_globs:
      - light.*
      - cover.*
      - fan.*

google_assistant:
  project_id: home-assistant-19f4f
  service_account: !secret google_assistant_service_account
  report_state: true
  expose_by_default: false
  entity_config:
    sensor.xiaomi_pm25: { expose: true }
    fan.xiaomi_miio_device: { expose: true }
    climate.apartment: { expose: true }
    cover.living_room_shades: { expose: true }
    light.living_room_lights: { expose: true }
    light.kitchen_cove_lights: { expose: true }
    light.kitchen_lights: { expose: true }
    light.front_foyer_lights: { expose: true }
    light.joes_room_lights: { expose: true }
    light.joes_room_lights: { expose: true }

ecobee:
  api_key: !secret ecobee_api_key

lutron_caseta:
  - host: 10.0.0.194
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

zwave:
  usb_path: /dev/zwave
  network_key: "0x04, 0xD1, 0xD6, 0x19, 0x30, 0xFF, 0x6B, 0x71, 0x54, 0x38, 0x4C, 0x79, 0x5A, 0x31, 0x24, 0xFD"

zha:
  usb_path: /dev/zigbee
  database_path: /config/zigbee.db

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1
  birth_message:
    topic: tele/hass1/LWT
    payload: Online
    qos: 1
    retain: false
  will_message:
    topic: tele/hass1/LWT
    payload: Offline
    qos: 1
    retain: false

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_token
    parse_mode: markdown
    trusted_networks: 127.0.0.1
    allowed_chat_ids:
      - -427766023 # Apartment chat
      - 1252020315 # Evan DM
      - 1050261397 # Joe DM

fan:
  # Xaiomi Airpurifier 2S. Token obtained using the miio client. Network access
  # is restricted to the localnetwork only.
  - platform: xiaomi_miio
    name: Air Purifier
    host: 10.0.0.25
    token: a0210ed9910d5d5698743a17cdd521ff

sensor:
  - platform: template
    sensors:
      xiaomi_temperature:
        friendly_name: Temperature (Purifier)
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'temperature') }}"
        unit_of_measurement: '°C'
        device_class: temperature
      xiaomi_humidity:
        friendly_name: Humidity (Purifier)
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'humidity') }}"
        unit_of_measurement: '%'
        device_class: humidity
      xiaomi_pm25:
        friendly_name: pm25
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'aqi') }}"
        unit_of_measurement: 'µg/m3'
        # Device class is not supported for pm25, however giving it the name of
        # 'pm25' will allow homekit to pickup that it is an air quality sensor.
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast: [1]
    monitored_conditions: [temperature]

binary_sensor:
  - platform: template
    sensors:
      front_door:
        # The door sensor alternates between the values 23 and 22 for closed
        # and open respectively.
        value_template: "{{ is_state('sensor.door_state', '22') }}"
        device_class: door
        friendly_name: Front Door

cover:
  - platform: group
    name: Living Room Shades
    entities:
      - cover.living_room_left_shade
      - cover.living_room_middle_shade
      - cover.living_room_right_shade
