- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Systemd user daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: /run/user/1000
