- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Systemd user daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: evan
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ evan_uid.stdout }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ evan_uid.stdout }}/bus"
