- name: Install zrepl packages
  community.general.apk:
    name:
      - zrepl
      - zrepl-openrc
    state: present

- name: Ensure zrepl configuration directory
  ansible.builtin.file:
    path: /etc/zrepl
    state: directory
    mode: "0755"

- name: Install zrepl configuration
  ansible.builtin.copy:
    src: zrepl.yml
    dest: /etc/zrepl/zrepl.yml
    mode: "0644"
  notify: Restart zrepl

- name: Enable zrepl service
  ansible.builtin.service:
    name: zrepl
    enabled: true
