- name: Install wireless network config
  ansible.builtin.template:
    src: purkhiser
    dest: /etc/netctl
    mode: "0600"

- name: Enable wireless network config
  ansible.builtin.command:
    cmd: netctl enable purkhiser
    creates: /etc/systemd/system/multi-user.target.wants/netctl@purkhiser.service
