---
- name: Enable bluetooth service
  service: name=bluetooth enabled=yes state=started

- name: Install bluetooth udev rules
  copy: src=10-bluetooth.rules dest=/etc/udev/rules.d/

# Bluetooh pairing of the controller is done manually for now due to the fact
# that pairing the device is pretty finicky.
#
# The process for paring the device is:
#
# - Start bluetoothctl (as root)
# - power on
# - agent on
# - default-agent
# - scan on
#
# - Put the NES30 controller into discoverability mode. This is done by turning
#   the device on (hold start for 3 seconds) and hold select for 5-7 seconds.
#   At some point the device should be detected (you may have to turn it on and
#   off a few times).
#
# - trust <controller MAC address>
# - pair <controller MAC address>
# - connect <controller MAC address>
#
# Once the device is paired it will stay paired.
