---
- name: Install required packages
  pacman: name={{ item }}
  with_items:
    - bash-completion
    - vim
    - git
    - nfs-utils
    - xorg-server
    - xorg-xinit
    - xf86-video-intel
    - bluez
    - bluez-utils
    - kodi
    - lirc
    - polkit
    - media-center-automation

- name: Install wireless network config
  template: src=purkhiser dest=/etc/netctl mode=0600

- name: Enable wireless network config
  command: netctl enable purkhiser creates=/etc/systemd/system/multi-user.target.wants/netctl@purkhiser.service

- name: Disable tty1 post-boot screen clear
  copy: src=noclear.conf dest=/etc/systemd/system/getty@tty1.service.d/

- include: lirc.yml
- include: bluetooth.yml
- include: kodi.yml
