---
- name: Install required packages
  pacman: name=bash-completion,vim,git,nfs-utils,xorg-server,xorg-xinit,\
               xf86-video-intel,bluez,bluez-utils,kodi,lirc,polkit,\
               media-center-automation

- name: Configure wireless network
  template: src=wlp2s0-Purkhiser dest=/etc/netctl mode=0600

- include: lirc.yml
- include: bluetooth.yml
- include: kodi.yml
