- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart atuin
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - pod-atuin
    - container-atuin-postgres
    - container-atuin-server
    - container-atuin-abacus
