- name: Ensure transmission configuration directory exists
  ansible.builtin.file:
    path: /home/evan/.config/transmission-daemon
    state: directory
    owner: evan
    group: users
    mode: "0755"

- name: Ensure transmission runs as "evan"
  ansible.builtin.copy:
    src: transmission-user.conf
    dest: /etc/systemd/system/transmission-daemon.service.d/
    mode: "0644"

- name: Read existing transmission settings
  ansible.builtin.slurp:
    src: /home/evan/.config/transmission-daemon/settings.json
  register: machines_existing_transmission_settings
  failed_when: false

- name: Ensure transmission configuration
  vars:
    existing: "{{ machines_existing_transmission_settings.content | default('e30=') | b64decode | from_json }}"
    desired: "{{ lookup('file', 'transmission-settings.json') | from_json }}"
  ansible.builtin.copy:
    content: "{{ existing | combine(desired) | to_nice_json }}\n"
    dest: /home/evan/.config/transmission-daemon/settings.json
    mode: "0644"
  notify: Reload transmission

- name: Enable transmission daemon
  ansible.builtin.service:
    name: transmission-daemon
    state: started
    enabled: true
    daemon_reload: true

- name: Install transmission-helper config
  ansible.builtin.copy:
    dest: /etc/transmission-helper.conf
    mode: "0600"
    content: |
      OPENAI_API_KEY={{ transmission_helper.openai_api_key }}
      TELEGRAM_TOKEN={{ transmission_helper.telegram_token }}

- name: Install transmission-helper organization config
  ansible.builtin.copy:
    dest: /etc/transmission-helper.yaml
    mode: "0644"
    content: |
      transmission:
        baseUrl: http://localhost:9091/
      telegram:
        chatId: "-722956237"
      moveCompleteDir: /mnt/documents/downloads/torrents-seeding/other
      sentryDsn: https://254c85b83a782bab95ddca042bff1625@o126623.ingest.us.sentry.io/4509976585437184

      categories:
        movies:
          layout: movie
          path: /mnt/documents/multimedia/videos/movies
          prompt: Anything that is a feature-length film or otherwise considered a movie.
          label: Movie
          examples:
            - |
              "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP.mkv"
              -> layout: "movie"
                 category: "movies"
                 title: "The Dark Knight"
                 filePath: "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP.mkv"
            - |
              "Toy.Story/Toy.Story.rar"
              -> Extract using unrar_file tool
              -> Tool returns ["Toy.Story/Toy.Story.mkv"], this list of files is considered with the rest of the torrent files.
              -> Do NOT include the archive itself as a filePath in the final output.
              -> layout: "movie"
                 category: "movies"
                 title: "Toy Story"
                 filePath: "Toy.Story/Toy.Story.mkv"
            - |
              "A.Star.Is.Born.1976.mkv"
              -> Web Search "a star is born" to see if the year is an important factor.
              -> layout: "movie"
                 category: "movies"
                 title: "A Star Is Born (1976)"
                 filePath: "A.Star.Is.Born.1976.mkv"
        anime:
          layout: series
          path: /mnt/documents/multimedia/videos/anime
          prompt: A Japanese anime series produced and animated in Japan. Supersedes TV series, but anime movies should still use the movies category.
          label: Anime
          examples:
            - |
              "Frieren.S01E01.1080p.WEB-DL.mkv"
              -> layout: "series"
                 category: "anime"
                 seriesTitle: "Frieren: Beyond Journey's End"
                 season: 1
                 episode: 1
                 filePath: "Frieren.S01E01.1080p.WEB-DL.mkv"
        tv-series:
          layout: series
          path: /mnt/documents/multimedia/videos/series
          prompt: A TV Series with seasons / episodes.
          label: TV Series
          examples:
            - |
              "Breaking.Bad.S01E01.Pilot.1080p.WEB-DL.x264/S01E01.mkv"
              -> layout: "series"
                 category: "tv-series"
                 seriesTitle: "Breaking Bad"
                 season: 1
                 episode: 1
                 filePath: "Breaking.Bad.S01E01.Pilot.1080p.WEB-DL.x264/S01E01.mkv"

- name: Install transmission-helper systemd service
  ansible.builtin.copy:
    src: transmission-helper@.service
    dest: /etc/systemd/system/transmission-helper@.service
    mode: "0644"

- name: Install transmission-helper systemd socket activation
  ansible.builtin.copy:
    src: transmission-helper.socket
    dest: /etc/systemd/system/transmission-helper.socket
    mode: "0644"

- name: Enable transmission helper socket activatiojn
  ansible.builtin.service:
    name: transmission-helper.socket
    state: started
    enabled: true
    daemon_reload: true

- name: Install transmission-helper trigger script
  ansible.builtin.copy:
    src: transmission-helper-trigger.sh
    dest: /usr/local/bin/transmission-helper-trigger.sh
    mode: "0777"

- name: Install transmission-helper handler script
  ansible.builtin.copy:
    src: transmission-helper-handler.sh
    dest: /usr/local/bin/transmission-helper-handler.sh
    mode: "0766"

- name: Register transmission as tailscale service
  tailscale_service:
    name: transmission
    local_port: 9091
