darksky_api_key: '{{ home_assistant.darksky_api_key }}'
spotify_api_key: '{{ home_assistant.spotify_api_key }}'
spotify_username: '{{ home_assistant.spotify_username }}'
spotify_password: '{{ home_assistant.spotify_password }}'
google_assistant_api_key: '{{ home_assistant.google_assistant_api_key }}'
