# Configure udev rules for the zigbee / zwave adapter
- name: Ensure zigbee / zwave rules
  notify: Reload udev rules
  ansible.builtin.copy:
    src: 99-usb-gocontrol.rules
    dest: /etc/udev/rules.d/
    mode: "0644"
