---
- name: Add arch ZFS repo
  copy: src=archzfs-repo dest=/etc/pacman.d

- name: Include config in pacman.conf
  lineinfile: dest=/etc/pacman.conf line="Include = /etc/pacman.d/archzfs-repo"
  notify: sync pacman cache

- name: Install required packages
  pacman: name={{ item }}
  with_items:
  - bash-completion
  - vim
  - nfs-utils
  - dnsmasq
  - mosquitto
  - transmission-cli
  - wget
  - rsync
  - rclone
  - nginx
  - homebridge-git
  - homebridge-tasmota-git
  - waitress
  - archzfs-linux

  # Required for encrypting the transmission basic auth password
  - python2-passlib

# Configure network
- name: Disable default network configuration
  file: path=/etc/systemd/network/80-container-host0.network state=link src=/dev/null

- name: Ensure systemd-networkd is enabled
  service: name=systemd-networkd state=started enabled=yes

- name: Ensure hosts file
  copy: src=hosts dest=/etc/

# Copy network configurations
- name: Set wan0 link name
  copy: src={{ item }} dest=/etc/systemd/network/
  notify: restart systemd-networkd
  with_items:
  - 00-lan0.link
  - 00-wan0.link
  - 01-internal.network
  - 01-external.network

# Setup iptable rules
- name: Configure iptables
  copy: src=iptables.rules dest=/etc/iptables/
  notify: [ 'restart iptables', 'restart ip6tables' ]

- name: Link iptable rules for v6 rules
  file: path=/etc/iptables/ip6tables.rules state=link src=/etc/iptables/iptables.rules

- name: Ensure iptables is enabled
  service: name=iptables enabled=yes state=started

# Setup and configure DHCP and DNS server
- name: Configure dnsmasq
  copy: src=dnsmasq.conf dest=/etc/
  notify: restart dnsmasq

- name: Ensure dnsmasq is enabled
  service: name=dnsmasq enabled=yes state=started

# Enable mosquito service for IoT messages
- name: Ensure mosquitto is enabled
  service: name=mosquitto enabled=yes state=started

# Configure rclone
- name: Ensure rclone backup configuration
  template: src=rclone.conf dest=/etc/rclone.conf

- name: Install rclone timer and service
  copy: src=rclone-sync.{{item}} dest=/etc/systemd/system/
  with_items: [ timer, service ]

- name: Enable rclone timer service
  service: name=rclone-sync.timer enabled=yes

# Configure NFS shares
- name: Enable nfs-server service
  service: name=nfs-server state=started enabled=yes

- name: Enable nfs rpcbind socket activation (nfs v2/3)
  service: name=rpcbind.socket enabled=yes

- name: Ensure documents device is exported
  copy: src=exports dest=/etc/exports
  notify: reload nfs exports

# Configure nginx server
- name: Enable nginx server
  service: name=nginx state=started enabled=yes

- name: Ensure nginx server configuration
  copy: src=nginx.conf dest=/etc/nginx/
  notify: reload nginx

- name: Encrypt transmission basic-auth password
  htpasswd: path=/etc/nginx/htpasswd_transmission
            mode=600
            owner=http
            name=evan
            password={{ transmission_rpc_password }}

# Configure transmission
- name: Ensure transmission configuration directory exists
  file: path=/home/evan/.config/transmission-daemon state=directory

- name: Ensure transmission runs as "evan"
  copy: src=transmission-user.conf dest=/etc/systemd/system/transmission.service.d/

- name: Ensure transmission configuration
  copy: src=transmission-settings.json dest=/home/evan/.config/transmission-daemon/settings.json
  notify: reload transmission

- name: Enable Transmission daemon
  service: name=transmission state=started enabled=yes

# Configure personal arch packages repo
- name: Ensure transmission configuration directory exists
  file: path=/srv/packages state=directory

# Configure homebridge
- name: Ensure homebridge config
  copy: src=homebridge.json dest=/var/lib/homebridge/config.json
        owner=homebridge
        group=homebridge
  notify: restart homebridge

- name: Ensure homebridge persit directory
  file: path=/var/lib/homebridge state=directory
        owner=homebridge
        group=homebridge

- name: Enable homebridge daemon
  service: name=homebridge state=started enabled=yes

# Enable waitress file server
- name: ensure waitress config
  copy: src=waitress.conf dest=/etc/waitress.conf
  notify: restart waitress

- name: Enable waitress service
  service: name=waitress state=started enabled=yes

# Configure DNS entires in cloudflare
- name: Ensuring DNS entries
  with_items: "{{ lookup('file', 'files/dns_records.yml') | from_yaml }}"
  cloudflare_dns:
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_token }}"

    state: present
    zone: evanpurkhiser.com
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    proxied: "{{ item.proxied | default('no') }}"
    content: "{{ item.content }}"
