# Configure network
- name: Disable default network configuration
  ansible.builtin.file:
    path: /etc/systemd/network/80-container-host0.network
    state: link
    src: /dev/null

- name: Ensure systemd-networkd is enabled
  ansible.builtin.service:
    name: systemd-networkd
    state: started
    enabled: true

- name: Ensure hosts file
  ansible.builtin.copy:
    src: hosts
    dest: /etc/
    mode: "0644"

- name: Ensure systemd-resolved is enabled
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: true

- name: Ensure resolved.conf file
  notify: Restart systemd-resolved
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: "0644"

- name: Ensure resolv.conf is linked to systemd-resolved stub
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Set interface names
  notify: Reload udev rules
  with_items:
    - 00-lan0.link
    - 00-wan0.link
  ansible.builtin.copy:
    src: network/{{ item }}
    dest: /etc/systemd/network/
    mode: "0644"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Configure networkd.conf
  notify: Require network intervention
  ansible.builtin.copy:
    src: network/networkd.conf
    dest: /etc/systemd/
    mode: "0644"

- name: Reconfigure network
  notify: Require network intervention
  with_items:
    - 01-internal.network
    - 01-external.network
  ansible.builtin.copy:
    src: network/{{ item }}
    dest: /etc/systemd/network/
    mode: "0644"

# Configure firewall
- name: UFW deny everything
  community.general.ufw:
    state: enabled
    policy: deny

- name: UFW allow local networking
  community.general.ufw:
    rule: allow
    from_ip: 10.0.0.0/24

- name: UFW limit SSH
  community.general.ufw:
    rule: limit
    port: 22
    interface_in: wan0

- name: UFW allow HTTP
  community.general.ufw:
    rule: allow
    port: 80
    interface_in: wan0

- name: UFW allow transmission
  community.general.ufw:
    rule: allow
    port: 51413
    interface_in: wan0

# Setup and configure DNS server
- name: Configure dnsmasq
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/
    mode: "0644"
  notify: Restart dnsmasq

- name: Create dnsmasq.service.d override directory
  ansible.builtin.file:
    path: /etc/systemd/system/dnsmasq.service.d
    state: directory
    mode: "0755"

- name: Override dnsmasq.service
  ansible.builtin.copy:
    dest: /etc/systemd/system/dnsmasq.service.d/override
    content: |
      [Service]
      # Small delay to ensure the lan0 device was correctly triggere dby udev
      ExecStartPre=/bin/sleep 1
    mode: "0644"

- name: Ensure dnsmasq is enabled
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
