# Configure rclone
- name: Ensure rclone backup configuration
  ansible.builtin.template:
    src: rclone.conf
    dest: /etc/rclone.conf
    mode: 0600

- name: Install rclone timer and service
  notify: Systemd daemon-reload
  with_items: [timer, service]
  ansible.builtin.copy:
    src: systemd/rclone-sync.{{ item }}
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable rclone timer service
  ansible.builtin.service:
    name: rclone-sync.timer
    state: started
    enabled: true

- name: Install rclone cryptcheck timer and service
  notify: Systemd daemon-reload
  with_items: [timer, service]
  ansible.builtin.copy:
    src: systemd/rclone-cryptcheck.{{ item }}
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable rclone cryptcheck timer service
  ansible.builtin.service:
    name: rclone-cryptcheck.timer
    state: started
    enabled: true

# Configure macOS file cleaner
- name: Install macOS file cleaner timer and service
  notify: Systemd daemon-reload
  with_items: [timer, service]
  ansible.builtin.copy:
    src: systemd/clean-macfiles.{{ item }}
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable macOS file cleaner timer service
  ansible.builtin.service:
    name: clean-macfiles.timer
    state: started
    enabled: true
