- name: Install instagram-saver config
  ansible.builtin.copy:
    dest: /etc/instagram-saver.conf
    mode: "0600"
    content: |
      GOOGLE_PLACES_API_KEY={{ instagram_saver.google_places_api_key }}
      OPENAI_TOKEN={{ instagram_saver.openai_token }}

- name: Ensure instagram-saver docker container
  containers.podman.podman_container:
    name: instagram-saver
    image: docker.io/evanpurkhiser/instagram-saver:latest
    state: present
    publish:
      - "9007:8888"
    env_file:
      - "/etc/instagram-saver.conf"
    label:
      io.containers.autoupdate: registry
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      new: true

- name: Ensure instagram-saver container is running
  ansible.builtin.systemd:
    name: container-instagram-saver
    state: started
    enabled: true
    daemon_reload: true
