- name: Ensure nginx server configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/
    mode: "0644"
  notify: Reload nginx

- name: Enable nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Encrypt transmission proxy basic-auth password
  community.general.htpasswd:
    path: /etc/nginx/htpasswd_transmission
    mode: "0600"
    owner: http
    name: evan
    password: "{{ nginx.transmission_rpc_password }}"

- name: Ensure Cloudflare origin cert
  ansible.builtin.copy:
    dest: /etc/ssl/cloudflare_origin.crt
    mode: "0600"
    content: "{{ nginx.cloudflare_cert }}"

- name: Ensure Cloudflare origin key
  ansible.builtin.copy:
    dest: /etc/ssl/cloudflare_origin.key
    mode: "0600"
    content: "{{ nginx.cloudflare_key }}"
