- name: Ensure atuin directories
  with_items:
    - atuin/data
    - atuin/config
  ansible.builtin.file:
    path: /var/lib/{{ item }}
    state: directory
    mode: "0755"

- name: Ensure atuin server.toml
  ansible.builtin.file:
    path: /var/lib/atuin/config/server.toml
    state: touch
    mode: "0644"

- name: Ensure atuin podman pod
  containers.podman.podman_pod:
    name: atuin
    infra_name: atuin-infra
    ports:
      - 7070:8888
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      new: true

- name: Ensure atuin postgres container
  containers.podman.podman_container:
    name: atuin-postgres
    image: docker.io/postgres:14
    state: present
    pod: atuin
    volumes:
      - "/var/lib/atuin/data:/var/lib/postgres/data"
    env:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: atuin
      POSTGRES_DB: atuin
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      new: true

- name: Ensure atuin server container
  containers.podman.podman_container:
    name: atuin-server
    image: ghcr.io/ellie/atuin:main
    state: present
    pod: atuin
    command: server start
    volumes:
      - "/var/lib/atuin/config:/config"
    env:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_PORT: 8888
      ATUIN_OPEN_REGISTRATION: false
      ATUIN_DB_URI: "postgres://atuin:atuin@localhost/atuin"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      new: true

- name: Ensure atuin containers are running
  with_items: [atuin-postgres, atuin-server]
  ansible.builtin.systemd:
    name: container-{{ item }}
    state: started
    enabled: true
    daemon_reload: true
