---
- name: Install required packages
  pacman: name={{ item }}
  with_items:
    - nginx

- name: Install eth0 network configuration
  copy: src=eth0.network dest=/etc/systemd/network/

- name: Enable IPv4 routing in the kernel
  copy: src=30-ipfward.conf dest=/etc/sysctl.d/

- name: Configure iptables
  copy: src=iptables.rules dest=/etc/iptables/
  notify: restart iptables

- name: Ensure iptables is enabled
  service: name=iptables enabled=yes state=started


# Configure nginx server
- name: Enable nginx server
  service: name=nginx state=started enabled=yes

- name: Ensure nginx server configuration
  copy: src=nginx.conf dest=/etc/nginx/
  notify: reload nginx
