---
- name: Install required packages
  pacman: name={{ item }}
  with_items:
    - nginx
    - mosquitto
    - atmosphere-automation

- name: Install eth0 network configuration
  copy: src=eth0.network dest=/etc/systemd/network/

- name: Enable IPv4 routing in the kernel
  copy: src=30-ipfward.conf dest=/etc/sysctl.d/

- name: Configure iptables
  copy: src=iptables.rules dest=/etc/iptables/
  notify: restart iptables

- name: Ensure iptables is enabled
  service: name=iptables enabled=yes state=started

# Configure nginx server
- name: Enable nginx server
  service: name=nginx state=started enabled=yes

- name: Ensure nginx server configuration
  copy: src=nginx.conf dest=/etc/nginx/
  notify: reload nginx

# Configure mosquitto mqtt server
- name: Enable mosquitto
  service: name=mosquitto state=started enabled=yes

# Configure atmosphere-automation service
- name: Ensure atmosphere-automation configuration
  template: src=atmosphere-automation.conf dest=/etc/
  notify: restart atmosphere-automation

- name: Enable atmosphere-automation
  service: name=atmosphere-automation state=started enabled=yes
