- name: Add user evan
  ansible.builtin.user:
    name: evan
    group: users
    groups: wheel
    password: "$6$DHaOCz9qtpA6ed5c$PEpj3xv8BQU9YrZx0djfgupmEUMgFx1kPmBc9AX3WdAcvj8TY8PXzWW3loI5VG8ENswqAt3fHN/07y.Jey8Zy0"

- name: Add authorized public ssh-key for "evan"
  ansible.posix.authorized_key:
    user: evan
    key: "{{ public_ssh_key }}"
    comment: personal
