- name: Add user evan
  ansible.builtin.user:
    name: evan
    group: users
    groups: wheel
    password: "$y$j9T$8gPAevjj5J6oH8FHcF.7W/$LNXTBA3OZun.4VC4clxiEoKFW7hjtB9UiLqIIrDShr/"

- name: Add authorized public ssh-key for "evan"
  ansible.posix.authorized_key:
    user: evan
    key: "{{ public_ssh_key }}"
    comment: personal
