server {
    listen 443 ssl;
    server_name apis.evanpurkhiser.com;

    location = /deploy-image {
        client_max_body_size 16k;
        proxy_pass http://127.0.0.1:19090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /meal-log {
        proxy_pass http://127.0.0.1:9006;
        proxy_request_buffering off;
        rewrite ^/meal-log(?:/(.*))?$ /$1 break;
    }

    location /atuin-abacus {
        proxy_pass http://127.0.0.1:7071;
        proxy_request_buffering off;
        rewrite ^/atuin-abacus(?:/(.*))?$ /$1 break;
    }

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location / {
        return 444;
    }
}
