server {
    listen 443 ssl;
    server_name apis.evanpurkhiser.com;

    location /meal-log {
        proxy_pass http://127.0.0.1:9006;
        proxy_request_buffering off;
        rewrite ^/meal-log(?:/(.*))?$ /$1 break;
    }

    location /instagram-saver {
        proxy_pass http://127.0.0.1:9007;
        proxy_request_buffering off;
        rewrite ^/instagram-saver(?:/(.*))?$ /$1 break;
    }

    location /atuin-abacus {
        proxy_pass http://127.0.0.1:7071;
        proxy_request_buffering off;
        rewrite ^/atuin-abacus(?:/(.*))?$ /$1 break;
    }

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location / {
        return 444;
    }
}
