server {
    listen 443 ssl;
    server_name dots.evanpurkhiser.com;

    proxy_hide_header Content-Security-Policy;
    add_header Content-Type text/plain;

    location / {
        # Specifying a resolver in the location block will stop nginx from
        # trying to resolve at boot, which is problematic when nginx is
        # started before internet is available.
        resolver 127.0.0.1 valid=30s;

        proxy_pass "https://raw.githubusercontent.com/evanpurkhiser/dots-personal/main/download";
    }
}
