server {
    listen 443 ssl;
    server_name public.evanpurkhiser.com;

    location / { proxy_pass http://127.0.0.1:9005; }

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }
}
