name: lint
on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint with ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible/ansible-lint@main
